name: Create magisk module

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Generate versions
      uses: HardNorth/github-version-generate@v1.4.0
      with:
        version-source: file
        version-file: module.prop
        version-file-extraction-pattern: '(?<=version=v).+'
    
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: '${{ github.event.repository.name }}-${{env.CURRENT_VERSION}}.zip'
        exclusions: '*.git* *.github*'
        
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "${{ github.event.repository.name }}-${{env.CURRENT_VERSION}}.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        artifactContentType: 'application/zip'
        allowUpdates: true
        name: "v${{env.CURRENT_VERSION}}"
        tag: "v${{env.CURRENT_VERSION}}"